### ISSUE TITLE
[v4] TypeScript is broken - "TS2307: Cannot find module '@gorhom/bottom-sheet' or its corresponding type declarations."

### ISSUE THREAD

**Issue by gran33** [gorhom/react-native-scroll-bottom-sheet#1040]
# Bug

Running TS and getting this error:
`TS2307: Cannot find module '@gorhom/bottom-sheet' or its corresponding type declarations.`
## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
|@gorhom/bottom-sheet | 4.4.0 |
|react-native | 0.69.2|
|react-native-reanimated | 2.9.1|
|react-native-gesture-handler | 2.4.0|

## Steps To Reproduce

1. Upgrading from v3
2. TS is angry :/
3. It wasn't like this in previous versions

Describe what you expected to happen:

1. TS to be happy
2. No TS error like `Cannot find module`

## Reproducible sample code

```
import { BottomSheetModal, BottomSheetModalProvider } from '@gorhom/bottom-sheet'; // TS is angry
...
const bottomSheetRef = useRef<BottomSheetModal>(null); TS is angry
...
bottomSheetRef?.current?.dismiss(); // TS is angry
...
```

**Comment by rizkiandrianto** [comment]
Is there any temporary workaround? @gran33

**Comment by OfficialDarkComet** [comment]
Instead of importing BottomSheetModal and BottomSheetModalProvider separately, just do:
```
import BottomSheet from "@gorhom/bottom-sheet"
```

Then, make sure ref is referencing an active component. So you use the ref prop of a component that is mounted and its ref is stored for you to later reference.

```
// ...

const bottomSheetRef = useRef(null)

return (
  <BottomSheet
    ref={bottomSheetRef}
  >
    {Your stuff}
  </BottomSheet>
)

```

...then you can use bottomSheetRef?.current?.dismiss()

Hope this helps! 😊

\- Logan (a.k.a DarkComet)
