### ISSUE TITLE
[v4] | [v2] The bottom sheet open if a go to another tab and then returns to the tab where I use it. ANDROID 

### ISSUE THREAD

**Issue by oillada** [gorhom/react-native-scroll-bottom-sheet#1077]
# Bug

## Environment info
| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.4.3   |
| react-native                    | 0.68.2  |
| react-native-reanimated         | ~2.8.0   |
| react-native-gesture-handler    | ~2.2.1  |

Using the enableLogging() when i press other tab the index change to 0 [BottomSheet::handleOnChange] index:0 animatedCurrentIndex:0, and this is why when I return to the Bottom Sheet tab it appears open.
On iOS this event doesn't fire.
Is there a way yo prevent this event to fire on ANDROID when i change to another tab?

## Steps To Reproduce

1. Change to another bottom tab
2. Return to the home tab

Describe what you expected to happen:

1. Bottom Sheet stays closed

## Reproducible sample code

https://user-images.githubusercontent.com/281594/187096544-c1dbc0cf-b54d-4d5d-85b2-9d50b5405e35.mov

This are the logs when I return to the bottom sheet tab
`[BottomSheet::render] animatedSnapPoints:0 animatedCurrentIndex:0 providedIndex:-1
[BottomSheetHandleContainer::handleContainerLayout] height:24
[BottomSheetContainer::handleContainerLayout] height:719.7142944335938
[BottomSheet::useAnimatedReaction::OnSnapPointChange] snapPoints:249.71429443359375
[BottomSheet::animateToPosition] currentPosition:0 position:249.71429443359375 velocity:0
[BottomSheet::handleOnAnimate] toIndex:0 fromIndex:0
[BottomSheet::animateToPositionCompleted] animatedCurrentIndex:0 animatedNextPosition:249.71429443359375 animatedNextPositionIndex:0
[BottomSheet::render] animatedSnapPoints:249.71429443359375 animatedCurrentIndex:0 providedIndex:-1`

**Comment by rahmanharoon** [comment]
any update on this issue

**Comment by AdamGBS** [comment]
I'm experiencing an issue where the onChange event in @gorhom/bottom-sheet is unexpectedly triggered with an index of 0 when I navigate to another navigator on Android. This causes the BottomSheet to open when returning to the tab, even though I haven’t interacted with it.

It seems specific to Android since it doesn’t happen on iOS. After enabling enableLogging, I noticed [BottomSheet::handleOnChange] index:0 animatedCurrentIndex:0 in the logs each time I switch tabs, which suggests onChange is being called automatically during navigation.

Is there any way to prevent this behavior on Android? Or perhaps a way to conditionally stop onChange from firing when switching tabs?
