### ISSUE TITLE
[v4] [documentation] [dead link] [react navigation integration]

### ISSUE THREAD

**Issue by Orivoir** [gorhom/react-native-scroll-bottom-sheet#1104]
# Bug

Hi, thank for job.
Sorry if this isn't the right place to report documentation issues.

I attempt integrate react navigation with bottom sheet also ive read the documentation at [Guide > React Navigation Integration](https://gorhom.github.io/react-native-bottom-sheet/react-navigation-integration) that indicate update `safeAreaInsets` prop at all navigators with unclear explain.
Also i want see example implementation provide with a link at the bottom screen:

> For more details regarding the implementation, please have a look at the [Navigator Example](https://github.com/gorhom/react-native-bottom-sheet/blob/master/example/src/screens/integrations/NavigatorExample.tsx).

But the link is dead.

I think this link is generated at this line:
https://github.com/gorhom/react-native-bottom-sheet/blob/406ba5222418706c6ba79293aa4e4186b6527942/react-navigation-integration/index.html#L18
But the file is condensed/compiled hardy to read.

## Is there a working integration example for v4 somewhere?
 
Sorry for my bad english is not my native language.  

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | ^4.4.4   |
| react-native                    | 0.69.5  |
| react-native-reanimated         | ~2.9.1   |
| react-native-gesture-handler    | ~2.5.0  |

## Steps To Reproduce

1. Go at the [doc file](https://gorhom.github.io/react-native-bottom-sheet/react-navigation-integration)
2. Click at the bottom link with title **Navigator Example**

Describe what you expected to happen:

1. I expected link Navigator Example is not dead

## Reproducible sample code

Not useful

**Comment by paulrostorp** [comment]
I created https://github.com/gorhom/react-native-bottom-sheet/pull/1128 to address this, but I quickly realised others have fixed it too...

There are **a lot** of PR's attempting to address this @gorhom :
- https://github.com/gorhom/react-native-bottom-sheet/pull/1128
- https://github.com/gorhom/react-native-bottom-sheet/pull/1112
- https://github.com/gorhom/react-native-bottom-sheet/pull/1101
- https://github.com/gorhom/react-native-bottom-sheet/pull/1091
- https://github.com/gorhom/react-native-bottom-sheet/pull/1079
- https://github.com/gorhom/react-native-bottom-sheet/pull/1047

Edit:
A few more have been created since:
- https://github.com/gorhom/react-native-bottom-sheet/pull/1158
- https://github.com/gorhom/react-native-bottom-sheet/pull/1138
