### ISSUE TITLE
[v4] | [v2] Bottomsheet Randomly appearing when keyboard becomes visible

### ISSUE THREAD

**Issue by sahil-ahuja-1** [gorhom/react-native-scroll-bottom-sheet#1233]
# Bug -- iOS

Hello! I'm seeing a bug in which the bottomsheet randomly pops up when I enter a TextEdit / the keyboard becomes visible after tapping somewhere else on the page. The component that's gaining focus has nothing to do with the bottomsheet, but for some reason the bottomsheet is appearing overtop.

This doesn't happen reliably (maybe 1/30 times) does the bottomsheet appear.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            |  4.3.1  |
| react-native                    | 0.67.3  |
| react-native-reanimated         |  2.8.0  |
| react-native-gesture-handler    |  2.4.2  |

## Steps To Reproduce

1. Click on a text field somewhere else on the screen
2. Bottomsheet appears

## sample code

<img width="413" alt="Screenshot 2022-12-18 at 3 36 32 PM" src="https://user-images.githubusercontent.com/101741806/208318145-2022bf1c-9067-4fe4-a516-e26b92a582dd.png">

**Comment by traxx10** [comment]
Same issue here

**Comment by pierroo** [comment]
Facing exactly the same issue!
Oddly enough, only happen on android, and for some users with the "swiftkey" keyboard, bugs disappear when using GBoard...

Not sure if that helps, but yes, issue is exactly as described above.

For now I will handle the opening of the bottom through the state rather than the ref to make sure it's not even mounted at all so no risk to appear magically when keyboard opens.

Those ref opening bottomsheet brings a lot of weird issue.
They sometimes even open when navigating to the screen including them, even with an index of -1!
Completely random.

Edit: did you manage to fix it @sahil-ahuja-1 or @traxx10 ?

**Comment by zachdorcinville21** [comment]
Same issue here, @gorhom any thoughts on this issue?

**Comment by AdamGBS** [comment]
Same issue here

**Comment by jgudo** [comment]
Same issue on android.  The bottom sheet appears whenever the keyboard is dismissed/closed or when an TextInput blurs.

**Comment by AdamGBS** [comment]
@jgudo Maybe try to upgrade your package to the last version if you didn't, I did and it fixed the behaviour 🤷

**Comment by jgudo** [comment]
@AdamGBS I am using the latest version but this behavior still exists. I have posted a [Stack Overflow question](https://stackoverflow.com/questions/75873878/react-native-gorhom-bottom-sheet-collapses-opens-when-keyboard-dismiss-or-input)  regarding this. Although I have found some workaround by setting  a fixed height to the root component. However, with this workaround, I am facing another issue with keyboard avoiding views when it comes to TextInputs.  
I have tried a few props related to keyboard such as, tweaking them, to no avail.
```
keyboardBlurBehavior="none"
android_keyboardInputMode="adjustResize"
keyboardBehavior="fillParent"
```` 
Weirdly enough, when I changed my keyboard mode to a floating mode, bottom sheet works perfectly. So I highly suspect this is caused by the keyboard behavior. I am still waiting for a proper solution for this one.  I haven't tested it on iOS though.

**Comment by fluorescent23** [comment]
Did you guys find any solution? @jgudo @zachdorcinville21 @pierroo

**Comment by pierroo** [comment]
> Did you guys find any solution? @jgudo @zachdorcinville21 @pierroo

The only solution is to display the sheet through the state rather than through ref;
so it's rebuilding the sheet each time I call it but I guess it's necessary to avoid all those weird side effects

**Comment by katwal-dipak** [comment]
Same issue here! It seems the issue appears while using `BottomSheetTextInput`. When replaced with the react-native default `TextInput`, the issue is gone. The issue occurs when the BottomSheet is closed before the keyboard.

The solution that worked for me: 
Wrapping the content with `PanGestureHandler` and manually closing the keyboard.
And for `BottomSheetBackdrop` disable close if Keyboard is visible: 
` pressBehavior={isKeyboardVisible ? 'none' : 'close'}`

I also have to downgrade to `v 4.4.5` to avoid crashes which is another bug related to keyboard issues with this library.

```
 <PanGestureHandler
  ref={panGestureRef}
  simultaneousHandlers={bottomSheetRef}
   onHandlerStateChange={onHandlerStateChange}>
       <Your content>
 </PanGestureHandler>
```

```
const onHandlerStateChange = event => {
    //Close the keyboard, to avoid the bug
    if (event.nativeEvent.state === State.BEGAN) {
      Keyboard.dismiss();
    }
  };
```

```
 <BottomSheet
      ref={bottomSheetRef}
      simultaneousHandlers={panGestureRef}
```

**Comment by caspg** [comment]
I had the same issue with random bottom sheet popping up. I'm using expo and setting `softwareKeyboardLayoutMode` to `pan` solved it. https://docs.expo.dev/versions/latest/config/app/#softwarekeyboardlayoutmode
