### ISSUE TITLE
[v4] [v2] backdrop only works with 2 or more snapPoints

### ISSUE THREAD

**Issue by malnajdi** [gorhom/react-native-scroll-bottom-sheet#1343]
# Bug
I was using react native 0.65, and v3.6.6 of this package  and now i upgraded to 0.73.9 and i also upgraded this package with reanimated to v2.
I noticed that starting from v4 the backdrop does not work with i only have 1 snap-point defined example:
```
const snapPoints = useMemo(() => ['50%'], []);
```
It was working fine before, now it's not working anymore.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | v4.4.5   |
| react-native                    | v0.73.9   |
| react-native-reanimated         | 2.14.4   |
| react-native-gesture-handler    | 2.9.0   |

## Steps To Reproduce

1. install latest version of this package and it's dependencies.
2. run the backdrop example with only 1 snap-point

Describe what you expected to happen:

1. backdrop should work even for 1 snap-point

## Reproducible sample code

https://github.com/malnajdi/react-native-bottom-sheet/blob/master/example/app/src/screens/advanced/BackdropExample.tsx

**Comment by mfkrause** [comment]
I also thought this was happening, but a little digging turns out this is expected when using the default BottomSheetBackdrop component or when using the [custom implementation from the docs](https://gorhom.github.io/react-native-bottom-sheet/custom-backdrop).

In the first case (default BottomSheetBackdrop component), the interpolation on the `opacity` style is configured so that the opacity will stay zero from the closed index (-1) up to the configured `disappearsOnIndex`. By default, `disappearsOnIndex` is `0`. Then, the opacity will be interpolated from the indexes `disappearsOnIndex` to `appearsOnIndex`. By default, `appearsOnIndex` is set to `1.` When you're only using one snap point however, index 1 will never be reached: There's only index 0 (and index -1 if your bottom sheet is closed). Therefore, the opacity of the backdrop component will **always** be zero. See:

https://github.com/gorhom/react-native-bottom-sheet/blob/1f0e93f51f36d82d063db39fdef05159a2ad6f01/src/components/bottomSheetBackdrop/BottomSheetBackdrop.tsx#L89-L97

To fix this, simply set `disappearsOnIndex` to -1 and `appearsOnIndex` to 0. This should lead to an correct interpolation (didn't try as I'm using a custom backdrop - see below).

If you're using the custom backdrop implementation from the docs, the interpolation looks like this:

```ts
const containerAnimatedStyle = useAnimatedStyle(() => ({
    opacity: interpolate(
      animatedIndex.value,
      [0, 1],
      [0, 1],
      Extrapolate.CLAMP
    ),
  }));
```

As you can see, this implementation also only interpolates between the indexes 0 and 1. However, as the maximum index is 0 when only using one snap point, nothing will ever be interpolated. Simply adjust the indexes accordingly:

```ts
const containerAnimatedStyle = useAnimatedStyle(() => ({
    opacity: interpolate(
      animatedIndex.value,
      [-1, 0],
      [0, 1],
      Extrapolate.CLAMP
    ),
  }));
```

So nothing really broken on this library's end, just a matter of configuration. However, this should probably be made more clear in the documentation.

**Comment by malnajdi** [comment]
@mfkrause thanks a lot. It was really confusing. Really appreciate the time you put into explaining the answer.

**Comment by Subhashish-Mishra** [comment]
You can pass the BottomSheetBackdrop with `disappearsOnIndex` as -1 and `appearsOnIndex` as 0 props to the backdropComponent prop of BottomSheet, see below

```javascript
<BottomSheet
  backdropComponent={(props) => (
    <BottomSheetBackdrop
      {...props}
      disappearsOnIndex={-1}
      appearsOnIndex={0}
    />
  )}
  ref={bottomSheetRef}
  snapPoints={["75%"]}
>
``` 
This works perfectly with single `snapPoints` given.
