### ISSUE TITLE
[v4] ReanimatedError: Tried to synchronously call a non-worklet function on the UI thread.

### ISSUE THREAD

**Issue by beqramo** [gorhom/react-native-scroll-bottom-sheet#1365]
# Bug

Hi,
I swipe down the modal to close it and it throws this error.
I think call to the function is wrong
<img width="439" alt="image" src="https://github.com/gorhom/react-native-bottom-sheet/assets/40486471/5e9d6a67-5a7e-49b8-b581-f2f270e58815">

<img width="446" alt="image" src="https://github.com/gorhom/react-native-bottom-sheet/assets/40486471/6b4175a2-da99-49a7-bfa0-936ff9422544">

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.4.6   |
| react-native                    | 0.71   |
| react-native-reanimated         | ~3.1.0   |
| react-native-gesture-handler    | ~2.9.0   |

**Comment by VadymMilan** [comment]
Issue:
Worklets/Reanimated crash with:
"Error: [Worklets] Tried to synchronously call a non-worklet function addListener/removeListener on the UI thread."

Root cause:
Conflict between react-native-dotenv, react-native-worklets, and react-native-reanimated@4.2.1, causing incorrect Worklets serialization.

Fix:

* Removed react-native-dotenv Babel plugin
* Switched to dotenv + process.env via app.config.ts
* Downgraded react-native-reanimated from 4.2.1 to 4.2.0
* Cleared Metro cache and rebuilt native dependencies

Result:

* Worklets errors disappeared
* BottomSheet works correctly
* Map, OTP, and other Reanimated screens are stable again
* No changes were required in BottomSheet or Carousel business logic
