### ISSUE TITLE
[v4] BottomSheetFlatList crashing with newArchEnabled=true

### ISSUE THREAD

**Issue by BagasNS** [gorhom/react-native-scroll-bottom-sheet#1578]
# Bug

app crashing both on ios and android, when items need to scroll using newArchEnabled=true
![image](https://github.com/gorhom/react-native-bottom-sheet/assets/36254694/f745c423-ea34-45e5-8d4c-b7abc49b9029)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.5.1   |
| react-native                    |  0.72.5   |
| react-native-reanimated         | 3.5.4   |
| react-native-gesture-handler    | 2.13.3   |

## Steps To Reproduce

1. install libs using yarn
2. enable new arch
3. create BottomSheet with BottomSheetFlatList
4. try to render data until container need to scroll

Describe what you expected to happen:

1. app not crashing with newArchEnabled=true
## Reproducible sample code

on this setup, 18 data need to be scrolled, and app are crashing

```js
      <BottomSheet
        snapPoints={['50%']}
        index={0}
      >
        <Box bg={'$coolGray200'} flex={1}>
          <BottomSheetFlatList style={{ flex: 1 }} data={[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]} renderItem={({ item }) => (
            <Text>{item}</Text>
          )}/>
        </Box>
      </BottomSheet>
```

but if i try to render only 3 data (doesn't need to be scrolled) app are fine

im trying change to plain flatlist, app running well except it can't scrolling, for now i manage to solve this problem by changing ```newArchEnabled=false```

**Comment by Rodrigo816** [comment]
I also having the same problem using fabric engine `newArchEnabled=true`
It happens when I use `<BottomSheetScrollView />` if I use `<BottomSheetView />` works but can't scroll.
If I disable newArchEnabled everything works fine.
```
    <BottomSheetModal
        ref={bottomSheetModalRef}
        enableDynamicSizing
        backdropComponent={renderBackdrop}>
        <BottomSheetScrollView bounces={false}>
          {children}
        </BottomSheetScrollView>
      </BottomSheetModal>
```
I
<h2 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.5em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; padding-bottom: 0.3em; border-bottom: 1px solid var(--borderColor-muted, var(--color-border-muted)); color: rgb(230, 237, 243); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Environment info</h2>

Library | Version
-- | --
@gorhom/bottom-sheet | 4.5.1 and 5.0.0-alpha.4
react-native | 0.72.5
react-native-reanimated | 3.5.4
react-native-gesture-handler | 2.6.0

**Comment by Martin2037** [comment]
do not close
same issue here

**Comment by DSKonstantin** [comment]
Any updates?
