### ISSUE TITLE
[v4] Exception in HostFunction: expected 0 arguments, got 1

### ISSUE THREAD

**Issue by Bashar-Alziq** [gorhom/react-native-scroll-bottom-sheet#1795]
I installed add react-native-reanimated and react-native-gesture-handler then added "react-native-reanimated/plugin" in the plugins at the end in babel.config.js file and add the BottomSheetModalProvider

**Comment by Lemarcitus** [comment]
I had a similar issue, because I was installing the package with "npm install react-native-reanimated", instead of "npm expo install react-native-reanimated"

https://docs.swmansion.com/react-native-gesture-handler/docs/fundamentals/installation
https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started/
