### ISSUE TITLE
[v4] Bottom Sheet Not Swipeable On First Render - iOS

### ISSUE THREAD

**Issue by branaust** [gorhom/react-native-scroll-bottom-sheet#818]
# Bug

When the page is initially rendered (whether it be on a simulator or physical device) the bottom sheet is unswipable. The only way to trigger the bottom sheet is by tapping the handle component. The strange part is that if I reload the app and navigate to the appropriate page, I can swipe the bottom sheet and can continue to do so even if I refresh the app again until I close the app and restart it again, only to find that the bottom sheet is again not working.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5  |
| react-native                    | 0.64.3   |
| react-native-reanimated         | 2.2.0   |
| react-native-gesture-handler    | 1.10.2  |

## Steps To Reproduce

1. Open iOS Simulator
2. Navigate to bottom sheet and attempt to swipe
3. Refresh the sim once (maybe twice) and see if you get a different outcome

Describe what you expected to happen:

1. When the user first renders the page, they should be able to swipe the bottom sheet.

## Reproducible sample code

**SNACK**
https://snack.expo.dev/@branaust/bottom-sheet-v4-reproducible-issue-template

**Comment by hirbod** [comment]
I think the cause here is prolly the same that causes this issue #803 

You have a `onChange` listener which triggers on mount, causing a re-render with useState. As soon this happens a lot of things start to go bad (losing ref, sometimes disappearing modal etc).

When I remove the onChange in your snack, the swipe gesture works on mount. I worked around all this issues using ref's and imperativeHandles in my child components to make my updates only based on those values or to update child elements this way instead of passing down props. As soon as a re-render happens in your modal, it is currently broken. I feel like some kind of memoization stuff is going bad.

**Comment by branaust** [comment]
https://github.com/expo/expo/issues/15681
