### ISSUE TITLE
Library Maintenance & Future

### ISSUE THREAD

**Issue by jspizziri** [gorhom/react-native-scroll-bottom-sheet#995]
# Feature Request

@gorhom this library seems to get a lot of use, and it does look like you're working on it still.

But it definitely looks like you're overwhelmed based on what I'm seeing on issues and pull requests. Are you open to more maintainers? How much oversight can you/do you want to provide if there are other contributors?

I'm trying to make a good decision around forking and trying to build a new community or not. I don't want to do that, but if there is no one to provide oversight it's probably necessary.

Thanks for the great lib, I appreciate all your work.

## Why it is needed

Filling this out so my issue doesn't get closed by a bot https://github.com/gorhom/react-native-bottom-sheet/issues/994

## Possible implementation
Filling this out so my issue doesn't get closed by a bot https://github.com/gorhom/react-native-bottom-sheet/issues/994

### Code sample

Filling this out so my issue doesn't get closed by a bot https://github.com/gorhom/react-native-bottom-sheet/issues/994

**Comment by hirbod** [comment]
I personally think that @gorhom is a truly underrated dev and he has done amazing libraries for RN - based on the downloads and stars, I think he is far away from his sponsoring goals and I think sponsoring him is the right motivation to get PRs and issues done. I exactly understand your feelings, since traction and reactions to issues have dropped. The only thing I can imagine would be more collaborators as you suggested and definitely more sponsors. 

I'll try to see if I can reach out to a few people and motivate for sponsoring.

**Comment by jspizziri** [comment]
Keep open

**Comment by jspizziri** [comment]
Keep open.

**Comment by jspizziri** [comment]
Keep open
